import Head from "next/head";

export default function SinglePostPage() {
  return (
    <>
      <Head>
        <title>Twilone</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/twiloneLogo2.png" />
      </Head>
      <main className="flex justify-center h-screen">
        <div>Post View</div>
      </main>
    </>
  );
} 
